app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
#models table for user 
class User(UserMixin,db.Model):
    __tablename__='users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index=True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_hash = db.Column(db.String(255))
    pitches= db.relationship('Pitch',backref='user',lazy="dynamic")

    @property
    def password(self):
        raise AttributeError("You cannot read the password attribute")

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'User{self.username}'
#pitch class definition
class Pitch(db.Model):
    __tablename__='pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch_id = db.Column(db.Integer)
    pitch_title = db.Column(db.String)
    pitch_body = db.Column(db.String)
    category= db.Column(db.String)
    like = db.Column(db.Integer)
    dislike = db.Column(db.Integer)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,id):
        pitches = Pitch.query.filter_by(pitch_id=id).all()
        return pitches

class Review(db.Model):

    __tablename__ ='reviews'

    id = db.Column(db.Integer,primary_key = True)
    review = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_review(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f"Review('{self.review}', '{self.posted}')"

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref='role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class PitchForm(FlaskForm):
    title = StringField("Pitch Title",validators=[Required()])
    pitch = TextAreaField('Write your pitch here')
    category = SelectField("Pitch category",choices=[('Pickup Lines','Pickup Lines'),('Interview Pitch','Interview Pitch'),('Product Pitch','Promotion Pitch')],validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField("Write something about yourself.",validators=[Required()])
    submit = SubmitField('Submit')

class ReviewForm(FlaskForm):
    review = TextAreaField('Leave a comment')
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
simple = SimpleMDE()

photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    app=Flask(__name__)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix ='/auth')

    #Creating the app configurations
    app.config.from_object(config_options[config_name])

    #Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    #Registering the blueprint
    from.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #setting config
    # from .request import configure_request
    # configure_request(app)

    #Configure UploadSet
    configure_uploads(app,photos)

    #Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from .import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import PitchForm,UpdateProfile,ReviewForm
from ..import db,photos
from ..models import User,Pitch,Review
from flask_login import login_required,current_user
import markdown2

#Views
@main.route("/")
def index():
    """
    View root page function that return the index page and its data
    """
    pitches = Pitch.query.all()

    title = "Home - ideapitch"
    return render_template('index.html',title=title,pitches=pitches)

@main.route("/post",methods=['GET','POST'])
@login_required
def post():
    form = PitchForm()
    if form.validate_on_submit():
        title = form.title.data
        pitch = form.pitch.data
        category= form.category.data
        like=0
        dislike=0

        # Updated pitch instance
        new_pitch = Pitch(pitch_title=title,pitch_body=pitch,category=category,like=like,dislike=dislike,user=current_user)

        # save pitch method
        new_pitch.save_pitch()
        return redirect(url_for('main.post'))

    title="Post your pitch"
    return render_template('post.html',title=title,pitch_form=form)

@main.route('/pitch_review/<int:id>',methods=['GET','POST'])
@login_required
def pitch_review(id):
    pitch=Pitch.query.get_or_404(id)
    comment= Review.query.all()
    form=ReviewForm()

    if request.args.get("like"):
        pitch.like = pitch.like+1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch_review/{pitch_id}".format(pitch_id=pitch.id))

    elif request.args.get("dislike"):
        pitch.dislike=pitch.dislike+1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch_review/{pitch_id}".format(pitch_id=pitch.id))

    if form.validate_on_submit():
        review = form.review.data

        new_review = Review(id=id,review=review,user_id=current_user.id)

        new_review.save_review()
        return redirect(url_for('main.pitch_review',id=id))
    reviews = Review.query.all()
    return render_template('pitch_review.html',comment=comment,pitch=pitch,review_form=form,reviews=reviews)

@main.route('/user/<uname>')
def profile(uname):
    user=User.query.filter_by(username=uname).first()
    pitches = Pitch.query.filter_by(user_id=user.id).all()

    if user is None:
        abort(404)

    return render_template("profile/profile.html",user=user,pitches=pitches)

@main.route('/user/<uname>/update',methods=['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form=form)

@main.route('/user/<uname>/update/pic',methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename= photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar Block -->
{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block styles %}
  {{super()}}
  <!-- Importing the simple mde css and js files -->
  {{simplemde.css}}
  {{ simplemde.js}}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="shortcut icon" href="https://icon2.kisspng.com/20180320/upw/kisspng-computer-icons-idea-incandescent-light-bulb-clip-a-black-idea-icon-5ab0cae1715936.7716735415215357134643.jpg">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bad+Script|Indie+Flower|Loved+by+the+King|Srisakdi" rel="stylesheet">
{% endblock %}

{% block content %}
  <h1>404 error page not found</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro%}

<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="shortcut icon" href="https://icon2.kisspng.com/20180320/upw/kisspng-computer-icons-idea-incandescent-light-bulb-clip-a-black-idea-icon-5ab0cae1715936.7716735415215357134643.jpg">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bad+Script|Indie+Flower|Loved+by+the+King|Srisakdi" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="jumbotron">
</div>
<div class="text-center">
<a href="/post" class="btn btn-primary btn-lg">Create your Pitch</a>
</div>
<br>

  {% for pitch in pitches  %}
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
       <div class="panel">
       <div class="panel-body">
           <h2>{{ pitch.pitch_title }}</h2>
           <h4>{{ pitch.category}}</h4>

           <p>{{ pitch.pitch_body }}</p>
           <div class="text-center">
             <div class="col-md-6">
            <a href="/pitch_review/{{pitch.id}}?like=1" ><i   class="fas fa-thumbs-up"> {{pitch.like}}</i></a>
           </div>
           <div class="col-md-6">
            <a href="/pitch_review/{{pitch.id}}?dislike=1"> <i  class="fas fa-thumbs-down">  {{ pitch.dislike}}</i></a>
           </div>
           </div>

           <blockquote >
             <footer>Posted by:
               <cite > {{ pitch.user.username}}</cite>
               on
               <cite > {{ pitch.posted.strftime('%Y-%m-%d')}}</cite>
             </footer>
           </blockquote>
           <div class="text-center">
           <a href="/pitch_review/{{pitch.id}}" class="btn btn-primary">Comment</a>
         </div>
         </div>
       </div>
     </div>
   {% endfor %}
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">HOME</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a></li>


              {% if current_user.is_authenticated %}
                <li style="color:white;padding:15px;"><{{current_user.username}}</li>
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign Out</a></li>
              {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign In</a></li>
              {% endif %}

            </ul>
        </div>

    </div>
</div>

app/templates/pitch_review.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
<!-- Content block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="shortcut icon" href="https://icon2.kisspng.com/20180320/upw/kisspng-computer-icons-idea-incandescent-light-bulb-clip-a-black-idea-icon-5ab0cae1715936.7716735415215357134643.jpg">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bad+Script|Indie+Flower|Loved+by+the+King|Srisakdi" rel="stylesheet">
{% endblock %}


{% block content %}
  <!-- <div class="row"> -->
  <div class="col-xs-12 col-sm-4 col-md-5 col-lg-5">
       <div class="panel">
       <div class="panel-body">
           <h2>{{ pitch.pitch_title }}</h2>
           <h4>{{ pitch.category}}</h4>

           <p>{{ pitch.pitch_body }}</p>
           <div class="text-center">
             <div class="col-md-6">
            <a href="/pitch_review/{{pitch.id}}?like=1" ><i   class="fas fa-thumbs-up"> {{pitch.like}}</i></a>
           </div>
           <div class="col-md-6">
            <a href="/pitch_review/{{pitch.id}}?dislike=1"> <i  class="fas fa-thumbs-down">  {{ pitch.dislike}}</i></a>
           </div>
           </div>

           <blockquote >
             <footer>Posted by:
               <cite > {{ pitch.user.username}}</cite>
               on
               <cite > {{ pitch.posted.strftime('%Y-%m-%d')}}</cite>
             </footer>
           </blockquote>
           <div class="text-center">
           <a href="/pitch_review/{{pitch.id}}" class="btn btn-primary">Comment</a>
         </div>
         </div>
       </div>
     </div>

        <div class="col-md-4">
          <div class="panel">
            <div class="panel-body">

            {{ wtf.quick_form(review_form) }}
            {{simplemde.load}}
        </div>
      </div>
      </div>

<div class="col-md-12">
    <h2><span class="panel">Comments</span></h2>
    {%for comment in comment %}
         <div class="well" style="width: 25rem">
             <p>{{ comment.review}}</p>
             <p>Time posted: {{ comment.posted.strftime('%Y-%m-%d')}}</p>
       </div>
     {% endfor %}
</div>
{% endblock %}

app/templates/post.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="shortcut icon" href="https://icon2.kisspng.com/20180320/upw/kisspng-computer-icons-idea-incandescent-light-bulb-clip-a-black-idea-icon-5ab0cae1715936.7716735415215357134643.jpg">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bad+Script|Indie+Flower|Loved+by+the+King|Srisakdi" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="jumbotron">
</div>

<h3 class="text-center">Enter your pitch in the form below</h3>

        <div id="post-form" class="col-md-4">
          <div class="panel">
            <div class="panel-body">

            {{ wtf.quick_form(pitch_form) }}
            {{simplemde.load}}

        </div>
      </div>
    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}


{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="shortcut icon" href="https://icon2.kisspng.com/20180320/upw/kisspng-computer-icons-idea-incandescent-light-bulb-clip-a-black-idea-icon-5ab0cae1715936.7716735415215357134643.jpg">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bad+Script|Indie+Flower|Loved+by+the+King|Srisakdi" rel="stylesheet">
{% endblock %}

{% block content %}

  <div class="row">
    <!-- displaying Username -->
    <div id="bio"class="col-md-4">
      <h3> {{user.username | capitalize}}</h3>
      <!-- Displaying user bio -->
      {% if user.bio %}
        <p>{{user.bio}}</p>
      {% else %}
        <p> {{user.username|capitalize}} has no bio </p>
      {% endif %}

      {% if user == current_user %}
        <a href="{{url_for('main.update_profile',uname=user.username)}}" class="btn btn-danger">Edit profile</a>
      {% endif %}
    </div>

    <!-- Displaying profile photo -->
    <div class="col-md-4">
      {% if user.profile_pic_path %}
        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
      {% else %}
        <p>No profile picture</p>
      {% endif %}

      {% if user == current_user %}
        <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
          <input type="file" name="photo" class="form-control"required>
          <div class="text-center">
            <input type="submit" class="btn btn-danger btn-lg">
          </div>
        </form>
      {% endif %}

    </div>
  </div>

  {% for pitch in pitches %}
  <!-- <div class="row"> -->
  <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
       <div class="panel">
       <div class="panel-body">
           <h2>{{ pitch.pitch_title }}</h2>
           <h4>{{ pitch.category}}</h4>

           <p>{{ pitch.pitch_body }}</p>
           <div class="text-center">
             <div class="col-md-6">
            <a href="/pitch_review/{{pitch.id}}?like=1" ><i   class="fas fa-thumbs-up"> {{pitch.like}}</i></a>
           </div>
           <div class="col-md-6">
            <a href="/pitch_review/{{pitch.id}}?dislike=1"> <i  class="fas fa-thumbs-down">  {{ pitch.dislike}}</i></a>
           </div>
           </div>

           <blockquote >
             <footer>Posted by:
               <cite > {{ pitch.user.username}}</cite>
               on
               <cite > {{ pitch.posted.strftime('%Y-%m-%d')}}</cite>
             </footer>
           </blockquote>
           <div class="text-center">
           <a href="/pitch_review/{{pitch.id}}" class="btn btn-primary">Comment</a>
         </div>
         </div>
       </div>
     </div>
   {% endfor %}

{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link rel="shortcut icon" href="https://icon2.kisspng.com/20180320/upw/kisspng-computer-icons-idea-incandescent-light-bulb-clip-a-black-idea-icon-5ab0cae1715936.7716735415215357134643.jpg">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Slabo+27px" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bad+Script|Indie+Flower|Loved+by+the+King|Srisakdi" rel="stylesheet">
{% endblock %}


{% block content %}
<div class="container">
<div class="well">
  {{wtf.quick_form(form)}}
</div>
</div>
{% endblock %}